[package]
name = "decodering-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
decodering-core.workspace = true
decodering-db.workspace = true
decodering-raft.workspace = true
decodering-auth.workspace = true

actix-web.workspace = true
actix-cors.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing-actix-web.workspace = true
futures-util.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
rand.workspace = true
base64.workspace = true
serde_with.workspace = true
zeroize.workspace = true
uuid.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true

[dev-dependencies]
reqwest.workspace = true
actix-http.workspace = true

[lints]
workspace = true
