// @generated by quicktype — do not edit by hand.
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub enum Capability {
    #[serde(rename = "kv.delete")]
    KvDelete,

    #[serde(rename = "kv.read")]
    KvRead,

    #[serde(rename = "kv.taint")]
    KvTaint,

    #[serde(rename = "kv.versioning")]
    KvVersioning,

    #[serde(rename = "kv.write")]
    KvWrite,

    #[serde(rename = "lease.issue")]
    LeaseIssue,

    #[serde(rename = "lease.renew")]
    LeaseRenew,

    #[serde(rename = "lease.revoke")]
    LeaseRevoke,

    #[serde(rename = "rotation.policy")]
    RotationPolicy,

    #[serde(rename = "sync.manage")]
    SyncManage,

    #[serde(rename = "sync.run")]
    SyncRun,

    #[serde(rename = "sync.status")]
    SyncStatus,
}

#[derive(Serialize, Deserialize)]
pub struct DeleteInput {
    pub path: String,
}

#[derive(Serialize, Deserialize)]
pub struct DeleteOutput {
    pub deleted: bool,
}

#[derive(Serialize, Deserialize)]
pub struct DestroyInput {
    pub path: String,
}

#[derive(Serialize, Deserialize)]
pub struct DestroyOutput {
    pub destroyed: bool,
}

#[derive(Serialize, Deserialize)]
pub struct ReadInput {
    pub secret_name: String,

    pub version: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct ReadResponse {
    pub data: Option<serde_json::Value>,

    pub version: String,
}

#[derive(Serialize, Deserialize)]
pub struct RestoreInput {
    pub path: String,
}

#[derive(Serialize, Deserialize)]
pub struct RestoreOutput {
    pub restored: bool,
}

#[derive(Serialize, Deserialize)]
pub struct WriteInput {
    /// Arbitrary secret payload (any JSON value)
    pub data: Option<serde_json::Value>,

    pub path: String,
}

#[derive(Serialize, Deserialize)]
pub struct WriteOutput {
    pub version: String,
}
