[package]
name = "decodering-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde_yaml.workspace = true
extism.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
sha2.workspace = true
pem.workspace = true
x509-parser.workspace = true
rustls-webpki.workspace = true
rustls-pki-types.workspace = true
rsa.workspace = true
p256.workspace = true

[lints]
workspace = true
